return {
    {
        "nvim-treesitter/nvim-treesitter",
        -- dependencies = { "p00f/nvim-ts-rainbow" },
        opts = {
            ensure_installed = {
                "bash",
                "html",
                "javascript",
                "json",
                "lua",
                "markdown",
                "markdown_inline",
                "python",
                "query",
                "regex",
                "tsx",
                "typescript",
                "vim",
                "yaml",
                "go",
                "gomod",
                "gosum",
                "gowork",
            },
            sync_install = false,
            ignore_install = {},
            auto_install = true,
            highlight = {
                enable = true,
                additional_vim_regex_highlighting = false,
            },
            rainbow = {
                enable = true,
                extended_mode = true,
                max_file_lines = nil,
            },
        },
    },
}
